### ISSUE TITLE
Build Error: sf_utils.h

### ISSUE THREAD

**Issue by axelbr** [facebookresearch/nocturne#11]
Hi,
when running `python setup.py develop` the build process fails. The error message is the following:
`... include/utils/sf_utils.h:29:6: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type ...`

It seems there is a missing include in this file. The error can be resolved by adding 
`#include <memory>` to sf_utils.h.

**Comment by nathanlct** [comment]
Indeed that include seems to be missing, good catch!
Are you able to compile everything successfully with that fix?

Also do you know which version of SFML you installed? Trying to figure out why you got that error and we didn't.

**Comment by axelbr** [comment]
> Indeed that include seems to be missing, good catch! Are you able to compile everything successfully with that fix?

Yes, now I am able to compile everything.

> Also do you know which version of SFML you installed? Trying to figure out why you got that error and we didn't.

I am using SFML-2.5.1.

By the way, the dataset construction guide seems to be outdated (the file names changed etc.)
For instance, the directory `nocturne_utils` does not exist anymore.

**Comment by eugenevinitsky** [comment]
Wow, thank you for the catch. Opening up a PR to fix this now.

**Comment by eugenevinitsky** [comment]
https://github.com/facebookresearch/nocturne/pull/15

Are you trying to rebuild the dataset? Please let us know if you run into any issues; we've never had an external person try to build it and we'd love to be helpful if you run into issues.
