### ISSUE TITLE
Dataset Build Instructions

### ISSUE THREAD

**Issue by axelbr** [facebookresearch/nocturne#16]
Maybe let's continue this discussion (#11) here.

I ran into some issues during the dataset construction:

- [ ] The files/scripts referenced in the README were moved to the `scripts/` directory.
- [ ] There are dependencies needed to run `waymo_scenario_construction.py`, which are not mentioned in `environment.yml`: `tensorflow` and [`waymo-open-dataset-tf-2-x-0`](https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md).
- [ ] Running `make_solvable_files.py` does not accept command line arguments (maybe because of hydra?)
- [ ] Running `make_solvable_files.py` gives me this error: `PermissionError: [Errno 13] Permission denied: '/checkpoint'
`. After some debugging I figured out that the paths in `cfgs/config.yaml` should be relative paths. But I first have to look more into hydra.
- [ ] After fixing the paths, running `make_solvable_files.py` leads to the following error: `omegaconf.errors.ConfigKeyError: Key 'start_time' is not in struct`. I guess it should be `cfg['scenario']['start_time]`.

**Comment by eugenevinitsky** [comment]
Oof okay that's a fair number of issues. I'll open up a PR cleaning these particular ones up but in the meantime (so you're not blocked) you can also download the files directly from the dropbox if that's more convenient.

**Comment by eugenevinitsky** [comment]
Thank you for your help in pointing these errors out!

**Comment by axelbr** [comment]
Oh, I overlooked somehow that the construction progress is not mandatory. :smile: No problem.

**Comment by eugenevinitsky** [comment]
Taking a bit longer than I would have liked to debug all of this so thanks for your patience but I hope the pre-built dataset is working for you!

**Comment by axelbr** [comment]
No need to hurry.

**Comment by axelbr** [comment]
thanks for your help. i will try it on the weekend.
