### ISSUE TITLE
IndexError: _Map_base::at when running sim = Simulation()

### ISSUE THREAD

**Issue by BenQLange** [facebookresearch/nocturne#21]
Hi,

I've just installed your package. When running the example Python script from 'Installing Nocturne', I am getting the following error:

Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
from nocturne import Simulation
sim = Simulation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: _Map_base::at

Have I missed something during the installation process?

Thanks

**Comment by eugenevinitsky** [comment]
Hi! Sorry for the trouble. That's a leftover instruction in our README. Everything is fine, it's just that Nocturne requires a scenario file to construct the scenario. You can take a look at examples/create_env.py to see how to construct a scenario and there's an example json in there to use until you download the dataset.

**Comment by BenQLange** [comment]
Works! Thanks!
