### ISSUE TITLE
Problems with rendering.py

### ISSUE THREAD

**Issue by roggirg** [facebookresearch/nocturne#25]
Hi,
Thanks for sharing this awesome environment.

I'm trying to run rendering.py and end up with `IndexError`. 
It's happening at the third video creation with the following error:
`    source=scenario.getObjectsThatMoved()[3],
IndexError: list index out of range`

Same thing happens with the fourth video creation. It seems as though changing the index to `-1` for both works but I'm not sure if this is a sound change.

Thanks!

**Comment by eugenevinitsky** [comment]
Hi @roggirg ! Thanks for catching this. The only point of rendering.py is to show you how to make videos / images of the scenes so that change is totally sound but we'll also push a fix so that that doesn't happen again.

**Comment by roggirg** [comment]
Awesome thanks, I'll let you close this issue when you see fit.
