### ISSUE TITLE
Problems with mini dataset

### ISSUE THREAD

**Issue by roggirg** [facebookresearch/nocturne#26]
Hi again,

It seems as though the mini-dataset folders are missing `valid_files.json` which throws an error when running `create_env.py`. 
The full dataset has those files.

Thanks!

**Comment by roggirg** [comment]
Wow you are quick!!
Well I downloaded the full dataset so I'm okay. I'm guessing I can just use the same `valid_files.json` from the full dataset in the mini one, is that correct?

**Comment by eugenevinitsky** [comment]
Yep, that one should work with the mini-dataset!

**Comment by roggirg** [comment]
Cool, again I'll let you close this issue when you see fit.

**Comment by eugenevinitsky** [comment]
Thank you for catching this issue! We've added a new valid_files.json for the mini datasets if you want to re-download them; it'll let the environment run a little faster as we no longer have to check which files you have
