### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HandyClever** [facebookresearch/nocturne#40]
### Operating system

Ubuntu 2204

### Bug description

Hi there,

I encountered an error when executing nocturne/examples/create_env.py.

After the execution in a terminal, nothing showed up.

Before that, I strictly followed instructions and made sure every step was just the same as the readme file. And I've changed the 
DATA_ FOLDER to the place where the valid and train data are stored.

Any help would be greatly appreciated! Thanks in advance

### Steps to reproduce

strictly followed instructions and made sure every step was just the same as the readme file

### Relevant log output

```shell

```

**Comment by eugenevinitsky** [comment]
Yep! Simple fix, you need to go to cfgs/config.py and change the ```DATA_FOLDER``` to point to the path where you've downloaded the json files. Does that fix it?

**Comment by eugenevinitsky** [comment]
Did you do all the steps in the Downloading the Dataset section?

**Comment by HandyClever** [comment]
> Did you do all the steps in the Downloading the Dataset section?

Thanks for your reply~ I think I've changed the DATA_FOLDER path and made sure I followed every step until now
My current issue is that after the execution of create_env.py, nothing showed up

**Comment by HandyClever** [comment]
Oh, didn't know that. I thought it would pop up a window like the Carla simulator where we can have a peek at its visual

**Comment by eugenevinitsky** [comment]
Ah no, we should add an example that does that! I'm out tomorrow but I'll probably write one on Monday

**Comment by eugenevinitsky** [comment]
Can I close this issue or do you have something outstanding? I'll ping you when the rendering window example is merged.

**Comment by HandyClever** [comment]
Thanks for the help! Yeah I don't have further problems~
