### ISSUE TITLE
[Feature] Pretrained agents

### ISSUE THREAD

**Issue by hzyjerry** [facebookresearch/nocturne#52]
### Feature

Hi, thanks for your effort opensourcing this work! 

I wonder if there is any plan on releasing the pretrained agents as reported in the paper?

**Comment by eugenevinitsky** [comment]
Hi! I wish we could; unfortunately the Waymo license precludes us from doing so. The paper I believe includes this warning in the section about the license.

**Comment by eugenevinitsky** [comment]
Closing, reopen if you have more questions!
