### ISSUE TITLE
[Bug] Mistake in continuous action space definition

### ISSUE THREAD

**Issue by roggirg** [facebookresearch/nocturne#56]
### Operating system

Ubuntu 20.04

### Bug description

There seems to be a (small) mistake in the code here:
https://github.com/facebookresearch/nocturne/blob/94fc821abb9a9c30f693614f96e36c9f4b83a544/nocturne/envs/base_env.py#L103

The high values should use the key 'x_upper_bound' instead of 'x_lower_bound'.

**Comment by eugenevinitsky** [comment]
Omg, that explains why continuous actions never worked. Great catch!

**Comment by eugenevinitsky** [comment]
Thanks again for catching the remaining lower->upper!!
