### ISSUE TITLE
[Question] How can I get the VisibleObjects?

### ISSUE THREAD

**Issue by KevinJeon** [facebookresearch/nocturne#68]
### Question

Hi, i want to get the visible other objects from ones' perspective! It seems like `VisibleObjects` is that function in C++. Can I avail it in Python?
 Thank u :)

**Comment by nathanlct** [comment]
You can!

Check out https://github.com/facebookresearch/nocturne/blob/main/examples/nocturne_functions.py around line 95, which gives an example usage, where the `object` argument is the source (perspective) vehicle.

**Comment by KevinJeon** [comment]
Thks for rapid repond :) 

Oh, I used that function. But I cant find the feature indicating of object ID. 

![image](https://github.com/facebookresearch/nocturne/assets/49419937/1002cd5f-3dee-4157-bc92-88128a068572)

Can I get the index of this visilbe object? (such as ID!)

Thks!!
